### ISSUE TITLE
panic: runtime error: slice bounds out of range [:47] with capacity 32

### ISSUE THREAD

**Issue by ldez** [tetafro/godot#19]
```console
$ cd $(mktemp -d)
$ git clone https://github.com/golang/go
$ cd go/src
$ golangci-lint run
ERRO [runner] Panic: godot: package "plugin" (isInitialPkg: true, needAnalyzeSource: true): runtime error: slice bounds out of range [:47] with capacity 32: goroutine 17556 [running]:
runtime/debug.Stack(0x11f3471, 0x3c, 0xc002d293c8)
	runtime/debug/stack.go:24 +0x9f
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1(0xc0056c0550)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x1be
panic(0x10c0460, 0xc01169d7a0)
	runtime/panic.go:965 +0x1b9
github.com/tetafro/godot.checkCommentForPeriod(0xc015e51e50, 0x1, 0xa, 0xc007db45d0, 0x2d, 0xc00e9d9c80, 0x32, 0x1391, 0x96, 0x1, ...)
	github.com/tetafro/godot@v1.4.6/checks.go:78 +0x498
github.com/tetafro/godot.checkComments(0xc016906000, 0x3, 0x3, 0x119741f, 0xc, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	github.com/tetafro/godot@v1.4.6/checks.go:37 +0x2da
github.com/tetafro/godot.Run(0xc00e601380, 0xc00149f440, 0x119741f, 0xc, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
	github.com/tetafro/godot@v1.4.6/godot.go:63 +0x2b0
github.com/golangci/golangci-lint/pkg/golinters.NewGodot.func1.1(0xc0108b0d00, 0xdabcf294, 0x1aad340, 0xc00f8f4538, 0x2)
	github.com/golangci/golangci-lint/pkg/golinters/godot.go:50 +0x1a9
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc0056c0550)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:187 +0x9f2
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x2a
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc0019699a0, 0x113b7ec, 0x5, 0xc0031d3770)
	github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x4d
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc0056c0550)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:104 +0x91
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc00ee7bad0, 0xc0056c0550)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0x65
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x316 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: godot: package "plugin" (isInitialPkg: true, needAnalyzeSource: true): runtime error: slice bounds out of range [:47] with capacity 32
```

related to https://github.com/golangci/golangci-lint/issues/431#issuecomment-826168245

**Comment by tetafro** [comment]
Fixed in 1.4.7
